const sections = [
  {
    id: "information-we-collect",
    title: "Information We Collect",
    blocks: [
      {
        type: "p",
        content:
          "We collect information that is needed to operate Crew and provide its event and game features."
      },
      { type: "h3", content: "Account and profile information" },
      {
        type: "p",
        content: "When you create or use an account, we may collect:"
      },
      {
        type: "list",
        items: [
          "Full name",
          "Email address",
          "Password submitted for account registration and sign-in",
          "Date of birth",
          "Gender",
          "Profile picture, if you choose to upload one",
          "User ID, account role, account status, profile completion status, and email verification status"
        ]
      },
      { type: "h3", content: "Authentication and device information" },
      {
        type: "p",
        content:
          "We use authentication data to keep you signed in and protect your account. This may include:"
      },
      {
        type: "list",
        items: [
          "Access tokens and refresh tokens",
          "A randomly generated installation identifier stored on your device",
          "Standard network request data, such as IP address, request timestamps, and server logs"
        ]
      },
      {
        type: "p",
        content:
          "The installation identifier is generated by the app and is used for app functionality, account security, abuse prevention, and operational reliability. We do not use it for advertising or tracking."
      },
      { type: "h3", content: "Event, ticket, and check-in information" },
      {
        type: "p",
        content:
          "To provide event access and check-in features, we may collect and process:"
      },
      {
        type: "list",
        items: [
          "Event IDs and event participation information",
          "Ticket IDs, ticket status, entry codes, purchase or creation timestamps, price information, and check-in timestamps",
          "Venue check-in codes submitted by you",
          "Participant IDs, attendance state, and related event access records"
        ]
      },
      { type: "h3", content: "Game and multiplayer information" },
      {
        type: "p",
        content:
          "To run real-time event games, matching, and scoreboards, we may collect and process:"
      },
      {
        type: "list",
        items: [
          "Match QR tokens and scanned opponent QR tokens",
          "Match invites, invite responses, match IDs, participant IDs, readiness state, match results, selected tasks, task acceptance or rejection, task completion state, and scoreboard entries",
          "Real-time WebSocket messages needed to synchronize event and match state"
        ]
      },
      { type: "h3", content: "Photos and camera use" },
      {
        type: "p",
        content:
          "If you choose to add a profile picture, the app lets you pick an image, crop it, and upload it as your profile picture. We only receive the image you choose to upload."
      },
      {
        type: "p",
        content:
          "Crew uses the device camera to scan QR codes during event game flows. Camera frames are used for QR scanning and are not uploaded as photos or videos. If a QR code is successfully scanned, the scanned QR token may be sent to our servers to create or respond to a game interaction."
      },
      { type: "h3", content: "Technical and support information" },
      {
        type: "p",
        content:
          "We may collect technical information needed to maintain, secure, and debug the service, such as server logs, API request metadata, error information, and device or network status relevant to connectivity. If you contact us for support, we may collect the information you choose to provide in that request."
      }
    ]
  },
  {
    id: "how-we-collect-information",
    title: "How We Collect Information",
    blocks: [
      {
        type: "p",
        content: "We collect information in the following ways:"
      },
      {
        type: "list",
        items: [
          "Directly from you, such as when you register, sign in, enter an event code, select a profile photo, or participate in a game.",
          "Automatically through app and server interactions, such as authentication, API requests, WebSocket connections, and standard server logs.",
          "From your device only with the relevant action or permission, such as using the camera to scan QR codes or using the system photo picker to select a profile image."
        ]
      }
    ]
  },
  {
    id: "how-we-use-information",
    title: "How We Use Information",
    blocks: [
      {
        type: "p",
        content: "We use information for the following purposes:"
      },
      {
        type: "list",
        items: [
          "Create, authenticate, verify, and manage user accounts",
          "Provide event discovery, tickets, QR access, venue check-in, and event participation",
          "Run real-time game sessions, matchmaking, invites, tasks, results, and scoreboards",
          "Display user profile information, such as name and profile picture, where needed for event and game features",
          "Send account-related emails, such as verification and password reset messages",
          "Maintain security, prevent abuse, detect unauthorized access, and protect the integrity of event and game flows",
          "Store your session locally so you can stay signed in",
          "Operate, troubleshoot, improve, and support the app and backend services",
          "Comply with legal obligations and enforce applicable terms"
        ]
      },
      {
        type: "p",
        content:
          "We do not use your information for third-party advertising, targeted advertising, or cross-app tracking."
      }
    ]
  },
  {
    id: "sharing-of-information",
    title: "Sharing of Information",
    blocks: [
      {
        type: "p",
        content: "We may share information only as needed to operate Crew."
      },
      { type: "h3", content: "With other Crew users" },
      {
        type: "p",
        content:
          "Some information may be visible to other participants in the same event or game context. This can include your name, profile picture, participant status, match status, game result, task state, and scoreboard information."
      },
      { type: "h3", content: "With service providers" },
      {
        type: "p",
        content:
          "We use service providers to operate the app and backend services, such as hosting, cloud storage, email delivery, networking, security, and operational infrastructure. These providers may process information only to provide services to us and must protect user data consistently with this Privacy Policy."
      },
      {
        type: "p",
        content:
          "Profile pictures may be uploaded to and served from cloud storage or a content delivery service. Remote images loaded by the app may also involve standard network requests to the relevant image host."
      },
      { type: "h3", content: "Legal and safety reasons" },
      {
        type: "p",
        content:
          "We may disclose information if required by law, legal process, or governmental request, or if we believe disclosure is necessary to protect users, prevent fraud or abuse, investigate security issues, or protect our rights."
      },
      { type: "h3", content: "Business transfers" },
      {
        type: "p",
        content:
          "If Crew is involved in a merger, acquisition, financing, reorganization, or sale of assets, user information may be transferred as part of that transaction, subject to appropriate confidentiality and privacy protections."
      }
    ]
  },
  {
    id: "tracking-advertising-analytics",
    title: "Tracking, Advertising, and Analytics",
    blocks: [
      {
        type: "p",
        content: "Crew does not:"
      },
      {
        type: "list",
        items: [
          "Sell personal information",
          "Share personal information with data brokers",
          "Use the Apple IDFA for tracking",
          "Use App Tracking Transparency tracking permissions",
          "Include third-party advertising networks",
          "Use personal information for third-party targeted advertising"
        ]
      },
      {
        type: "p",
        content:
          "If our practices change, we will update this Privacy Policy and the App Store privacy disclosures before using information for new purposes where required."
      }
    ]
  },
  {
    id: "app-permissions",
    title: "App Permissions",
    blocks: [
      {
        type: "p",
        content: "Crew may request the following permissions:"
      },
      {
        type: "list",
        items: [
          "Camera: used to scan QR codes for event game flows. Camera images or videos are not uploaded.",
          "Photo picker: used only when you choose a profile image. Crew does not require full access to your photo library."
        ]
      },
      {
        type: "p",
        content:
          "Crew does not request access to your precise location, contacts, microphone, health data, or fitness data for the features described in this policy."
      }
    ]
  },
  {
    id: "local-storage",
    title: "Local Storage",
    blocks: [
      {
        type: "p",
        content:
          "The app may store authentication tokens, user profile data, and a randomly generated installation identifier on your device so the app can keep you signed in and provide account functionality. Deleting the app may remove local app storage from your device, but it does not automatically delete server-side account, ticket, event, or game records."
      }
    ]
  },
  {
    id: "retention-and-deletion",
    title: "Retention and Deletion",
    blocks: [
      {
        type: "p",
        content:
          "We retain information for as long as reasonably necessary to provide the app, maintain event and game records, protect the service, comply with legal obligations, resolve disputes, and enforce applicable terms."
      },
      {
        type: "p",
        content: "In general:"
      },
      {
        type: "list",
        items: [
          "Account and profile information is retained while your account is active.",
          "Event, ticket, check-in, and game records may be retained as needed for event operations, safety, audit, fraud prevention, and legal purposes.",
          "Profile pictures are retained until they are replaced, removed, or deleted as part of an account deletion request, subject to backup and legal retention needs.",
          "Technical logs are retained only as long as reasonably needed for security, debugging, operations, and legal compliance."
        ]
      },
      {
        type: "p",
        content:
          "You may request access to, correction of, or deletion of your personal information by contacting us using the contact information below. We may need to verify your identity before processing a request. Some information may be retained where required by law or where necessary for security, fraud prevention, dispute resolution, or legitimate operational records."
      }
    ]
  },
  {
    id: "your-choices",
    title: "Your Choices",
    blocks: [
      {
        type: "p",
        content:
          "You can choose not to upload a profile picture. You can also deny or revoke camera permission in your device settings, although QR scanning features may not work without camera access."
      },
      {
        type: "p",
        content:
          "You may request deletion of your account or personal information by contacting us. If Crew provides an in-app account deletion flow, you may also use that flow."
      }
    ]
  },
  {
    id: "children",
    title: "Children",
    blocks: [
      {
        type: "p",
        content:
          "Crew is not directed to children under 13, and we do not knowingly collect personal information from children under 13. Users must also meet the age requirements that apply to the events they attend. If you believe a child has provided personal information to Crew, contact us and we will take appropriate steps to delete the information where required."
      }
    ]
  },
  {
    id: "international-processing",
    title: "International Processing",
    blocks: [
      {
        type: "p",
        content:
          "Your information may be processed and stored in countries other than your country of residence. Where required, we use appropriate safeguards for international transfers of personal information."
      }
    ]
  },
  {
    id: "security",
    title: "Security",
    blocks: [
      {
        type: "p",
        content:
          "We use reasonable technical and organizational measures to protect information. However, no method of transmission or storage is completely secure, and we cannot guarantee absolute security."
      }
    ]
  },
  {
    id: "changes-to-this-policy",
    title: "Changes to This Policy",
    blocks: [
      {
        type: "p",
        content:
          "We may update this Privacy Policy from time to time. If we make material changes, we will update the effective date and provide additional notice where required."
      }
    ]
  },
  {
    id: "contact",
    title: "Contact",
    blocks: [
      {
        type: "p",
        content: (
          <>
            If you have questions or requests about this Privacy Policy or your
            personal information, contact us at{" "}
            <a href="mailto:frtpkaan@gmail.com">frtpkaan@gmail.com</a>.
          </>
        )
      }
    ]
  }
];

function PolicyBlock({ block }) {
  if (block.type === "h3") {
    return <h3>{block.content}</h3>;
  }

  if (block.type === "list") {
    return (
      <ul>
        {block.items.map((item) => (
          <li key={item}>{item}</li>
        ))}
      </ul>
    );
  }

  return <p>{block.content}</p>;
}

export default function Home() {
  const renderSectionLinks = () =>
    sections.map((section) => (
      <a key={section.id} href={`#${section.id}`}>
        {section.title}
      </a>
    ));

  return (
    <main className="policy-page">
      <header className="site-header" aria-label="Crew">
        <a className="brand" href="#top" aria-label="Crew Privacy Policy">
          <img
            src="crew_black_logo.png"
            alt="Crew"
            width={1201}
            height={387}
          />
        </a>
        <a className="contact-link" href="mailto:frtpkaan@gmail.com">
          Contact
        </a>
      </header>

      <section id="top" className="hero" aria-labelledby="policy-title">
        <p className="eyebrow">Privacy Policy</p>
        <h1 id="policy-title">Crew Privacy Policy</h1>
        <p className="updated">Effective date: June 8, 2026</p>
        <p className="intro">
          This Privacy Policy explains how Crew collects, uses, shares, and
          protects information when you use the Crew mobile application and
          related services.
        </p>
        <p className="intro">
          Crew is a mobile app for real-world social events. Users can create an
          account, verify their email address, discover events, access event
          tickets and QR flows, check in at venues, and participate in real-time
          event games.
        </p>
      </section>

      <div className="content-shell">
        <aside className="toc" aria-label="Policy sections">
          <div className="toc-desktop">
            <p>Sections</p>
            <nav>{renderSectionLinks()}</nav>
          </div>

          <details className="toc-mobile">
            <summary>
              <span>Sections</span>
              <strong>Jump to section</strong>
            </summary>
            <nav>{renderSectionLinks()}</nav>
          </details>
        </aside>

        <article className="policy-content">
          {sections.map((section) => (
            <section key={section.id} id={section.id} className="policy-section">
              <h2>{section.title}</h2>
              {section.blocks.map((block, index) => (
                <PolicyBlock key={`${section.id}-${index}`} block={block} />
              ))}
            </section>
          ))}
        </article>
      </div>
    </main>
  );
}
